### ISSUE TITLE
3 года прошло. Плагин ещё актуален? 

### ISSUE THREAD

**Issue by ApayRus** [yasinuslu/meteor-metrika#1]
Последние коммиты были 3 года назад. Эта штука еще работает?

**Comment by yasinuslu** [comment]
I looked at the code, it should work if there is backwards compatibility for deps package because it has been renamed to tracker. We need to replace it with tracker to be safe. I'll check it when I'm on my computer, probably tonight. I hope yandex did not deprecate this API

**Comment by ApayRus** [comment]
Thanks, It's working! 
Sorry for russian, just I was thinking , that metrika are used only by russian speakers . 
Yes, it works , I can watch pages statistics. Thanks for you . :+1:
